services:
  pong-front:
    container_name: pong-front
    build:
      context: ./pong/back
    networks:
      - pong_network
    ports:
      - "8888:8888"

networks:
  pong_network:
    name: pong_network