services:
  pong-front:
    container_name: pong-front
    build:
      context: ./pong/front
    networks:
      - pong_network
    ports:
      - 8888:8888

  pong-back:
    container_name: pong-back
    build:
      context: ./pong/back
    networks:
      - pong_network

networks:
  pong_network:
    name: pong_network